### ISSUE TITLE
Highlight offset when text too long

### ISSUE THREAD

**Issue by stylesuxx** [bonafideduck/react-highlight-within-textarea#15]
When I input text or break lines until the scrollbars show, the highlights will be offset by one line. when scrolling back up it will align at some point again.

![Screenshot from 2021-03-27 13-37-44](https://user-images.githubusercontent.com/978192/112720937-a02d6180-8f01-11eb-89b2-cf322a3647b7.png)

**Comment by bonafideduck** [comment]
Thanks for bringing this up.  I can also easily reproduce it.  Unfortunately, trying to mimic the textarea with a backdrop seems to have many issues.  I have not been able to determine the root cause of this one.

I've considered biting the bullet and completely rewriting with a textarea completely built in React.  But that rapidly becomes complex.  I believe I have to recreate the cursor, detect and handle mouseclicks to move the click, autoscroll when the cursor goes out of focus, properly handle highlights and other items I haven't even dreamt of.  So if that ever happens, it is a long way off.

**Comment by stylesuxx** [comment]
Yes, I understand - I was imagining such complications when I decided that I want a textarea with highlighting, so I was happy to have found yours.

For my current use case I can set a fixed height of rows and that will allow me to work around it.

**Comment by bonafideduck** [comment]
@stylesuxx , I have a [preview](https://bonafideduck.github.io/rhwta-preview/) of 2.0.0-alpha.8 available with [sample code](https://github.com/bonafideduck/react-highlight-within-textarea/tree/nwb-2-alpha/src) that should fix this.  It is available on NPM.

**Comment by bonafideduck** [comment]
Version 2.0.0 should fix this.
