### ISSUE TITLE
Replace Draft.js with Slate.js

### ISSUE THREAD

**Issue by gajus** [bonafideduck/react-highlight-within-textarea#67]
https://www.slatejs.org/

Slate is in active development, whereas Draft is more or less abandoned.

**Comment by bonafideduck** [comment]
Thanks for the suggestion.  I will keep this in mind.  But since Draft.js currently is accomplishing what react-highlight-within-textarea needs, it is quite popular still, and it doesn't have a slew of CVEs against it, I won't be converting at this time.  I will keep an eye out for changes in support levels.  Honestly, I'd prefer stability of an "abandoned" app over the instability of an active branch.

| Statistic | Draft.js | Slate.js |
| --- | --- | --- |
| Version | 0.70.0 | 0.11.0 |
| Last Published | A day ago | A year ago |
| Weekly Downloads | 573,998 | 191,481 | 
| FIrst Commit | Feb. 22, 2016 | Sept. 11 2017 | 
| 2021 Commits | ~60 | ~550 |
| Commits | 1136 | 3711 |

**Comment by bonafideduck** [comment]
I also considered quill, but trying it out, I couldn’t get past the infinite loop problem,  [this article](https://medium.com/the-lead/why-we-moved-from-quill-to-slate-94f42aa54fec) mentions it is slow for long documents, and the last release is 3 years old.  So, maybe slate is the way to go for version 4.0.
