### ISSUE TITLE
Compatibility with Next.JS

### ISSUE THREAD

**Issue by mrzmyr** [bonafideduck/react-highlight-within-textarea#91]
<img width="961" alt="CleanShot 2022-02-06 at 14 33 17@2x" src="https://user-images.githubusercontent.com/746429/152683426-1c4fbc36-3639-4960-86c8-67d069d2b3b2.png">

Draft.JS runs into errors when working with Next.JS. This is a known issue and can be fixed by [creating a reusable emptyContentState like in this example.](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/universal/editor.js#L43-L53)

**Further reading**
- https://github.com/facebook/draft-js/issues/2427
- https://github.com/facebook/draft-js/issues/1199#issuecomment-331677160

**Comment by bonafideduck** [comment]
@mrzmyr , thank you for making me aware of this issue.  I'd like to better understand the root cause of this.

The properties of DraftJs require a string for value to be sent in:

115 [ `  value: PropTypes.string.isRequired,`](https://github.com/bonafideduck/react-highlight-within-textarea/blob/813c68cc1dfb3caecd6b56968091e4f404ab0dc9/src/HighlightWithinTextarea.js#L115)

And on the first call, we should be creating an EditorStat with that string as content.

51 [`    editorState = EditorState.createWithContent(contentState);`](https://github.com/bonafideduck/react-highlight-within-textarea/blob/813c68cc1dfb3caecd6b56968091e4f404ab0dc9/src/HighlightWithinTextarea.js#51)

Is the next.js code sending in 'undefined' for value?  If so, even though it violates the props contract, I can add a special handler for that.

**Comment by mrzmyr** [comment]
This is making problems because Next.JS is creating different instances on server and client. For more details see the explanation by @flarnie (Co-maintainer of Draft.js): https://github.com/facebook/draft-js/issues/1199#issuecomment-331677160

She is suggesting to [create a reusable emptyContentState](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/universal/editor.js#L43-L53).

I created a PR you can check out here: https://github.com/bonafideduck/react-highlight-within-textarea/pull/95
